name: Liquid C
favicon: null
layout_spectrum: 0.64486
typography_spectrum: 0.06924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0905'
    - '#a18b7d'
    - '#422c1e'
    - '#e1dbc2'
    - '#fafcfe'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
