name: Liquid C
favicon: null
layout_spectrum: 0.64486
typography_spectrum: 0.06924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0905'
    - '#a18b7d'
    - '#422c1e'
    - '#e1dbc2'
    - '#fafcfe'
  brandStrength: 0.4375
  lightness: 0.5790211562998593
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
